version: '3'
services:

  komodod:
    tty: true
    restart: always
    image: mykomodo:latest
    volumes:
     - ./data:/coin/data
     - ./coin.conf:/root/.komodo/komodo.conf
     - ./coin.conf:/coin/data/komodo.conf
    ports:
       - 13000:13000
       - 13001:13001

  komodod2:
    tty: true
    restart: always
    image: mykomodo:latest
    volumes:
     - ./data2:/coin/data
     - ./coin2.conf:/root/.komodo/komodo.conf
     - ./coin2.conf:/coin/data/komodo.conf
    ports:
       - 23000:13000
       - 23001:13001
    depends_on:
       - komodod
    links:
       - "komodod:komodod"

